Repository canonical/k8s-operator, pull requests merged in 2025-04, with the labels that each got.

#431 [Release 1.32] Update K8s revisions ["amd64-2907","arm64-2908"]
  charms/worker/k8s/templates/snap_installation.yaml
Labels: automerge

#423 feat: nightly multi ceph cluster tests
  .github/workflows/nightly.yaml
  charms/worker/k8s/tests/unit/test_base.py
  tests/integration/conftest.py
  tests/integration/data/ceph-manifest.yaml
  tests/integration/data/test-bundle-ceph.yaml
  tests/integration/data/test_storage_provider/ceph-xfs-pvc.yaml
  tests/integration/data/test_storage_provider/dynamic-pvc.yaml
  tests/integration/data/test_storage_provider/pv-reader-pod.yaml
  tests/integration/data/test_storage_provider/pv-writer-pod.yaml
  tests/integration/helpers.py
  tests/integration/storage.py
  tests/integration/terraform/ceph-manifest.yaml
  tests/integration/terraform/default-manifest.yaml
  tests/integration/terraform/main.tf
  tests/integration/terraform/setup.py
  tests/integration/test_ceph.py
  tests/integration/test_openstack.py
  tox.ini
Labels: trivial

#438 bug: Address issues where mulitple worker application join a k8s cluster
  charms/worker/k8s/charmcraft.yaml
  charms/worker/k8s/src/charm.py
Labels: backport

#442 [Release 1.32] Update K8s revisions ["amd64-3260","arm64-3171"]
  charms/worker/k8s/templates/snap_installation.yaml
Labels: automerge

#446 The promote-charm action needs the checked-out code for access to metadata
  .github/workflows/promote-charms.yaml
Labels: backport

#452 release: update revisions release 1.33
  .github/workflows/auto-update-libs-k8s-worker.yaml
  .github/workflows/bot_pr_approval.yaml
  .github/workflows/charm-analysis.yaml
  .github/workflows/comment.yaml
  .github/workflows/comment_contributing.yaml
  .github/workflows/integration_test.yaml
  .github/workflows/load_test.yaml
  .github/workflows/promote-charms.yaml
  .github/workflows/publish-charms.yaml
  charms/worker/k8s/templates/snap_installation.yaml
Labels: trivial
